### ISSUE TITLE
Comparing with GKRTree

### ISSUE THREAD

**Issue by zhouhao27** [emma-k-alexandra/RTree#4]
There is a `RTree` implementation in iOS `GameKit`. I'm wondering what's the difference between your implementation and the iOS implementation?

As I know your solution will store all nodes on disk? Am I right? Thanks.

**Comment by emma-k-alexandra** [comment]
Apple’s R-Tree implementation is very full featured and designed for in-memory, gaming level performance. 

This R-Tree implementation acts more like a database. The goal is to store all of your R-Tree data on disk and load the smallest amount of data possible into memory. Since I wrote this R-Tree implementation for my own use case, it only supports nearest neighbor queries since that’s all I needed (PRs welcome if you want to contribute).

I currently use this package for storing a large, geographic dataset with too many entries to store in memory, but needs all data to be queried from arbitrary geographic points. I also needed an R-Tree that works and loads quickly on watchOS, which the GameKit trees do not support.

**Comment by emma-k-alexandra** [comment]
There’s a similar explanation on my other package, [BTree](https://github.com/emma-k-alexandra/BTree#why-use-this-b-tree-as-opposed-to-btree) that covers this as well. Might add a similar section to this package’s README
